name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Get dependencies and build
      run: |
        yarn install
        yarn build
        cd dist && echo "<html><head><meta http-equiv="refresh" content="0; url=/"><title>404 Not Found</title></head><body><center><h1>404 Not Found</h1></center><hr><center>CloudMoe-GitHub</center></body></html>" > 404.html && cd ..
        
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: dist
        fqdn: aclsub.mojy.xyz
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
